language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"

cache:
    directories:
        - $HOME/.composer/cache/files

before_script:
    - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - vendor/bin/phpcs
    - vendor/bin/phpunit
