name: Run code sniffer

on: [push]

jobs:
  phpcs:
    name: Run code sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run code sniffer
        run: ./vendor/bin/phpcs
